- .travis.yml
- Makefile
- docs/publishing.md
[#169095100](https://www.pivotaltracker.com/story/show/169095100)
This PR will varify other branches and commits don't trigger publishing jobs.
> Publish docker images and helm charts on travis

- .travis.yml
- Makefile
- bin/publish-image
[#169095100](https://www.pivotaltracker.com/story/show/169095100)
Add a script to publish image
> Fix publish image error

- docs/examples/exjob_auto-errand-deletes-pod.yaml
- docs/examples/exjob_auto-errand-updating.yaml
- docs/examples/exjob_auto-errand-updating_updated.yaml
- docs/examples/exjob_auto-errand.yaml
- docs/examples/exjob_errand.yaml
- docs/examples/exjob_errand_updated.yaml
- docs/examples/exjob_output.yaml
- integration/auto_errand_job_test.go
- pkg/kube/apis/extendedjob/v1alpha1/types.go
- pkg/kube/controllers/extendedjob/errand_controller.go
- pkg/kube/controllers/extendedjob/errand_reconciler.go
- pkg/kube/controllers/extendedjob/errand_reconciler_test.go
- pkg/kube/controllers/extendedjob/job_creator.go
- pkg/kube/controllers/extendedjob/job_reconciler.go
- pkg/kube/controllers/extendedjob/job_reconciler_test.go
- pkg/kube/controllers/extendedjob/persist_output.go
- pkg/kube/controllers/extendedjob/persist_output_test.go
- pkg/kube/util/reference/configmap_references.go
- pkg/kube/util/reference/secret_references.go
- testing/catalog.go
[#169094953](https://www.pivotaltracker.com/story/show/169094953)
> Replace PodTemplateSpec with JobTemplateSpec

- deploy/helm/quarks-job/README.md
- deploy/helm/quarks-job/templates/cluster_role.yaml
- deploy/helm/quarks-job/templates/operator.yaml
- deploy/helm/quarks-job/values.yaml
Depends on https://github.com/cloudfoundry-incubator/cf-operator/pull/683
[#169095052](https://www.pivotaltracker.com/story/show/169095052)
> Updates to helm chart

- .gitignore
- README.md
- bin/include/docker
- bin/include/versioning
- deploy/helm/quarks-job/README.md
- deploy/helm/quarks-job/templates/NOTES.txt
- deploy/helm/quarks-job/templates/role.yaml
- docs/examples/exjob_auto-errand-deletes-pod.yaml
- docs/examples/exjob_auto-errand-updating.yaml
- docs/examples/exjob_auto-errand-updating_updated.yaml
- docs/examples/exjob_auto-errand.yaml
- docs/examples/exjob_errand.yaml
- docs/examples/exjob_errand_updated.yaml
- docs/examples/exjob_output.yaml
- docs/extendedjob.md
- go.mod
- go.sum
- integration/errand_job_test.go
- pkg/kube/apis/apis.go
- pkg/kube/controllers/extendedjob/persist_output_test.go
Requires: https://github.com/cloudfoundry-incubator/quarks-utils/pull/9
[#169095318](https://www.pivotaltracker.com/story/show/169095318)
> Rename API group name to "quarks.cloudfoundry.org"

- cmd/internal/root.go
- go.mod
- go.sum
- pkg/kube/controllers/extendedjob/errand_controller.go
- pkg/kube/controllers/extendedjob/job_controller.go
- pkg/kube/controllers/extendedjob/persist_output.go
Dependent PR's
1. https://github.com/cloudfoundry-incubator/quarks-utils/pull/12
2. https://github.com/cloudfoundry-incubator/cf-operator/pull/652
> Adapt to quarks-utils latest package

- pkg/kube/controllers/quarksjob/errand_controller.go
- pkg/kube/controllers/quarksjob/job_controller.go
[#169095334](https://www.pivotaltracker.com/story/show/169095334)
It's not a functional change, only a cleanup.
> Update controller names

- .travis.yml
- Dockerfile
- bin/build-image
- cmd/internal/persist_output.go
- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/controllers/quarksjob/job_reconciler.go
- pkg/kube/controllers/quarksjob/output_persistor.go
- pkg/kube/controllers/quarksjob/output_persistor_test.go
Preparing for [#169418463](https://www.pivotaltracker.com/story/show/169418463)
>  Remove instance group labels from quarks-job

- .dockerignore
- deploy/helm/quarks-job/templates/operator.yaml
- deploy/helm/quarks-job/templates/persist-output-role-binding.yaml
- deploy/helm/quarks-job/templates/persist-output-role.yaml
- deploy/helm/quarks-job/templates/persist-output-service-account.yaml
* create account in watch namespace if neccessary
* limit permissions
[#168884844](https://www.pivotaltracker.com/story/show/168884844)
> Add separate service account for persist output

- deploy/helm/quarks-job/templates/persist-output-role.yaml
[#168884844](https://www.pivotaltracker.com/story/show/168884844)
> Persist output needs more permissions on secrets

- integration/auto_errand_job_test.go
- integration/errand_job_test.go
- integration/suite_test.go
- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/controllers/quarksjob/job_controller.go
- pkg/kube/controllers/quarksjob/job_creator.go
[#169640900](https://www.pivotaltracker.com/story/show/169640900)
> Remove the bool label in favor of the qjob name label

- .travis.yml
- Makefile
- README.md
- bin/coverage
One part of [#169117636](https://www.pivotaltracker.com/story/show/169117636)
> Add godoc, report, coveralls badges

- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/controllers/quarksjob/output_persistor.go
- pkg/kube/controllers/quarksjob/output_persistor_test.go
[#170725085](https://www.pivotaltracker.com/story/show/170725085)
There is currently no way to tell the `OutputPersistor` to create not just one secret, but actually one secret per each key/value pair in the provided input.
In trying to keep as much as possible the way it was and to be backwards compatible, the `createSecret` function was "simplified" by moving the JSON parsing into `persistContainer` instead. Also the `createSecret` function signature only uses simple types, such as the name, the data, and so on.
Further logic is now in the `persistContainer` function, which has a switch to either perform the standard one-to-one persistence or fan-out style. With one-to-one, each entry in the output map will result in the configured secret. The new fan-out style takes the input file and …
> Introduce fan out persitence for link secrets

- deploy/helm/quarks-job/templates/_helpers.tpl
- deploy/helm/quarks-job/templates/cluster-role.yaml
- deploy/helm/quarks-job/templates/role-binding.yaml
- deploy/helm/quarks-job/templates/role.yaml
[#170601244](https://www.pivotaltracker.com/n/projects/2192232/stories/170601244)
> Restrict permissions to minimal in helm chart

- pkg/kube/controllers/quarksjob/output_persistor_test.go
The directory in which the flaky test case wrote the `provides.json` is
also used by other test cases and the directory being used is also
required to be present due to other test cases.
Create a temporary directory just for the test case and configure the
output persitor to use the temporary directory instead of `/tmp`.
> Fix flaky test case of output persistor

- .travis.yml
- deploy/helm/quarks-job/templates/_helpers.tpl
- deploy/helm/quarks-job/templates/role-binding.yaml
- deploy/helm/quarks-job/templates/role.yaml
[#170918922](https://www.pivotaltracker.com/story/show/170918922)
> Create role in watch namespace

- go.mod
- go.sum
- pkg/kube/apis/quarksjob/v1alpha1/register.go
[#168692418](https://www.pivotaltracker.com/n/projects/2192232/stories/168692418)
> Add preserveunknownfields field to crd spec

- .travis.yml
- bin/build-image
- integration/errand_job_test.go
- pkg/kube/apis/quarksjob/v1alpha1/register.go
- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/apis/quarksjob/v1alpha1/zz_generated.deepcopy.go
* remove unused Node field from status
[#170670921](https://www.pivotaltracker.com/story/show/170670921)
required by https://github.com/cloudfoundry-incubator/cf-operator/pull/819
> Add status to validation, to prevent pruning

- .travis.yml
- go.mod
- go.sum
Otherwise changes in git checkout will be cleared before we can push
them to s3.
Also bump to master of quarks-utils
> Travis publish needs skip_cleanup

- bin/test-unit
- go.mod
- go.sum
- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/controllers/quarksjob/output_persistor.go
- pkg/kube/controllers/quarksjob/output_persistor_test.go
* Sanitize secret names
* Store entanglement identifier key in labels
[#171417591](https://www.pivotaltracker.com/story/show/171417591)
[#171433464](https://www.pivotaltracker.com/story/show/171433464)
> Entanglement label

- .travis.yml
* support available versions on public providers
* bump kind to 0.7.0
> Update k8s versions to test

- pkg/kube/controllers/quarksjob/output_persistor.go
[#171615906](https://www.pivotaltracker.com/n/projects/2192232/stories/171615906)
> Sanitize secret labels

- .travis.yml
It's a hotfix for travis build.
> Get helm-v3 on travis

- .travis.yml
- go.mod
- go.sum
- integration/suite_test.go
- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/controllers/quarksjob/errand_controller.go
- pkg/kube/controllers/quarksjob/errand_reconciler.go
- pkg/kube/controllers/quarksjob/errand_reconciler_test.go
- pkg/kube/controllers/quarksjob/job_controller.go
- pkg/kube/controllers/quarksjob/job_creator.go
- pkg/kube/controllers/quarksjob/job_reconciler.go
- pkg/kube/controllers/quarksjob/job_reconciler_test.go
- pkg/kube/controllers/quarksjob/output_persistor.go
- pkg/kube/util/reference/reconciles.go
[#172047931](https://www.pivotaltracker.com/story/show/172047931)
I think this passed: https://travis-ci.org/github/cloudfoundry-incubator/quarks-job/builds/670143167
> Add namespaced logging messages

- .travis.yml
- bin/include/versioning
[#171492037](https://www.pivotaltracker.com/story/show/171492037)
> Add commit number as patch version

- .travis.yml
[#172397180](https://www.pivotaltracker.com/n/projects/2192232/stories/172397180)
> Add testing of kubernetes 1.17.0,1.18.0 in travis

- integration/auto_errand_job_test.go
- pkg/kube/apis/quarksjob/v1alpha1/register.go
- pkg/kube/apis/quarksjob/v1alpha1/types.go
- pkg/kube/controllers/quarksjob/errand_reconciler.go
- pkg/kube/controllers/quarksjob/job_reconciler.go
- pkg/kube/controllers/quarksjob/job_reconciler_test.go
[#166115464](https://www.pivotaltracker.com/story/show/166115464)
We can use it to provide qJob status transition.
> Add basic status track on qJob

- pkg/kube/controllers/quarksjob/namespace_predicate_test.go
- pkg/kube/controllers/quarksjob/service_account.go
Also fixes error message.
[#165900520](https://www.pivotaltracker.com/story/show/165900520)
> Add a test for namespace predicates

- pkg/kube/controllers/quarksjob/job_reconciler.go
- pkg/kube/util/reference/reconciles.go
[#165900520](https://www.pivotaltracker.com/story/show/165900520)
> Limit quarks jobs list to a namespace

- bin/include/testing
- go.mod
- go.sum
- integration/auto_errand_job_test.go
- integration/suite_test.go
Bumps quarks-utils for new version of shared scripts
https://github.com/cloudfoundry-incubator/quarks-utils/pull/51/
> Remove testing tmp dir functions

- .github/workflows/ci.yaml
- .github/workflows/golangci-lint.yml
- .github/workflows/publish.yml
- .golangci.yml
- bin/deploy
- bin/publish-helm-repo
- go.mod
- go.sum
Also removes the Makefile from CI, it's just another level of indirection and configs.
[#173009013](https://www.pivotaltracker.com/story/show/173009013)
> Linting and PRs

- .github/workflows/publish.yml
[#173660275](https://www.pivotaltracker.com/story/show/173660275)
> Only run publish on main repo

- pkg/kube/apis/quarksjob/v1alpha1/register.go
- pkg/kube/controllers/quarksjob/errand_reconciler.go
- pkg/kube/controllers/quarksjob/errand_reconciler_test.go
[#172323986](https://www.pivotaltracker.com/n/projects/2192232/stories/172323986)
The meltdown implmentation will delay the first trigger
for 10 seconds. The triggers happening in these 10 seconds
are skipped.
> Change meltdown implementation

- deploy/helm/quarks-job/values.yaml
- go.mod
- go.sum
- integration/environment/environment.go
- integration/environment/operator.go
- integration/suite_test.go
[#173218516](https://www.pivotaltracker.com/story/show/173218516)
> Use shared integration helpers

- .github/workflows/ci.yaml
- Dockerfile
- go.mod
- go.sum
[#172762728](https://www.pivotaltracker.com/story/show/172762728)
> Bump golang 1.14

- README.md
- cmd/docs/gen-command-docs.go
- go.mod
- go.sum
[#174254540](https://www.pivotaltracker.com/story/show/174254540)
> Don't generate CLI index page anymore

- .github/workflows/publish.yml
- Dockerfile
- go.mod
- go.sum
[#174667526](https://www.pivotaltracker.com/story/show/174667526)
> Bump quarks-utils to publish to ghcr.io

- .github/workflows/ci.yaml
- .github/workflows/publish.yml
- bin/deploy
- bin/publish-image
[#175181113](https://www.pivotaltracker.com/story/show/175181113)
> Publish to gchr.io

- .github/workflows/ci.yaml
- .github/workflows/golangci-lint.yml
- deploy/helm/quarks-job/templates/service-account-pull-secret.yaml
- deploy/helm/quarks-job/templates/service-account.yaml
- deploy/helm/quarks-job/values.yaml
[#175660052](https://www.pivotaltracker.com/n/projects/2192232/stories/175660052)
> Add support for registry authentication

- .github/workflows/ci.yaml
- Dockerfile
- go.mod
- go.sum
[#175984792](https://www.pivotaltracker.com/story/show/175984792)
> Bump go version to 1.15.8
