cloudfoundry-incubator/quarks-job

.travis.yml, integration/environment/operator.go, pkg/kube/controllers/extendedjob/errand_reconciler.go, pkg/kube/controllers/extendedjob/job_creator.go
Until the cf operator can use persist-output via the quarks-job binary,
provide compatibility in master
=> Use persist-output from specific cf-operator version

cmd/internal/root.go, e2e/cli/cli_test.go, go.mod, go.sum
This is using a branch of quarks-utils to avoid the incompatibilities in master.
=> Docker image tag defaults to quarks-job version

.travis.yml, Dockerfile, go.mod, go.sum, pkg/kube/controllers/extendedjob/errand_reconciler.go, pkg/kube/controllers/extendedjob/job_creator.go, pkg/kube/controllers/extendedjob/persist_output.go, pkg/kube/util/reference/reconciles.go
This reverts commits from https://github.com/cloudfoundry-incubator/quarks-job/pull/11
That PR was merged without it's corresponding PR in utils and breaks the public API. The utils PR for that change is untested with cf-operator master. To clear master for other PRs let's revert this, until the whole set of PRs is ready.
=> Revert "DRY up code by using the VersionedSecretStore"

cmd/internal/root.go, deploy/helm/quarks-job/templates/operator.yaml, e2e/cli/cli_test.go, integration/environment/environment.go, integration/environment/operator.go, integration/suite_test.go, pkg/kube/controllers/controllers.go, pkg/kube/controllers/quarksjob/errand_controller.go, pkg/kube/controllers/quarksjob/errand_reconciler.go, pkg/kube/controllers/quarksjob/errand_reconciler_test.go, pkg/kube/controllers/quarksjob/job_controller.go, pkg/kube/controllers/quarksjob/job_creator.go, pkg/kube/controllers/quarksjob/job_reconciler.go, pkg/kube/controllers/quarksjob/job_reconciler_test.go, pkg/kube/controllers/quarksjob/service_account.go, pkg/kube/operator/operator.go, pkg/kube/util/config/config.go
Use specified service account for persist-output container
Instead of creating a new service account with cluster admin
permissions, use the specified, pre-existing one.
The helm chart uses the same account for the operator and the
persist-output container.
* specify service account name on command line (SERVICE_ACCOUNT),
defaults to 'default'
* integration tests still create their own rolebinding and service
account
[#168884844](https://www.pivotaltracker.com/story/show/168884844)
=> Use pre-existing service account

deploy/helm/quarks-job/templates/cluster_role.yaml, deploy/helm/quarks-job/templates/operator.yaml, deploy/helm/quarks-job/templates/role.yaml, deploy/helm/quarks-job/templates/role_binding.yaml, deploy/helm/quarks-job/templates/service_account.yaml
This allows for `helm template --namespace x [...] | kubectl apply -f -`.
Also, we removed the namespace in `cluster_role.yaml`, because ClusterRole is not namespaced.
=> Add .Release.Namespace to helm template

bin/build-helm, deploy/helm/quarks-job/Chart.yaml, deploy/helm/quarks-job/README.md, deploy/helm/quarks-job/templates/_helpers.tpl, deploy/helm/quarks-job/templates/cluster-role.yaml, deploy/helm/quarks-job/templates/persist-output-role-binding.yaml, deploy/helm/quarks-job/templates/persist-output-role.yaml, deploy/helm/quarks-job/templates/persist-output-service-account.yaml, deploy/helm/quarks-job/templates/role-binding.yaml, deploy/helm/quarks-job/templates/role.yaml, deploy/helm/quarks-job/templates/service-account.yaml, deploy/helm/quarks-job/values.yaml
* rename rbacEnable to rbac.create
* only create rbac resources if rbac.create is true
* only create service account if create is true
* adapt documentation for service account
* templates should use dashes
https://helm.sh/docs/topics/chart_best_practices/rbac/
[#165014706](https://www.pivotaltracker.com/story/show/165014706)
=> Apply helm chart guidelines

bin/build-helm, bin/include/docker, bin/include/testing, bin/include/versioning, bin/test-cli-e2e, bin/test-integration, bin/test-unit
Helm follows semantic versioning and considers any version with dash to
be a pre-release.  Pre-releases are not found in search unless `--devel`
is used.
[#165014706](https://www.pivotaltracker.com/story/show/165014706)
=> Versioning: use build  separator

deploy/helm/quarks-job/values.yaml
The tag is replaced by bin/build-helm
=> Don't use a valid image tag in the helm template

Dockerfile
Docker base image is built on [OBS](https://build.opensuse.org/package/show/Cloud:Platform:quarks/quarks-operator-base).
[#171779755](https://www.pivotaltracker.com/story/show/171779755)
=> Switch OS to SLE

.travis.yml, bin/publish-helm-repo
[#171492037](https://www.pivotaltracker.com/story/show/171492037)
- Published helm release to https://github.com/cloudfoundry-incubator/quarks-helm and quarks-job release page on master branch
=> Publish helm release on github repo instead of s3

.travis.yml, bin/publish-helm-repo
Found a travis limit that `before_deploy runs for each deploy`: https://github.com/travis-ci/travis-ci/issues/2570#issuecomment-171262181
Even used that workaround, it still could not save helm artifacts between two deploys.
=> Remove github releases publish

cmd/internal/root.go, deploy/helm/quarks-job/templates/operator.yaml, deploy/helm/quarks-job/values.yaml, e2e/cli/cli_test.go, go.mod, go.sum, pkg/kube/util/config/config.go
Allows to set meltdown from CLI and helm chart
Requires https://github.com/cloudfoundry-incubator/quarks-utils/pull/42
[#170670255](https://www.pivotaltracker.com/story/show/170670255)
=> Configurable Meltdown

pkg/kube/apis/quarksjob/v1alpha1/types.go, pkg/kube/controllers/quarksjob/output_persistor.go, pkg/kube/controllers/quarksjob/output_persistor_test.go
[#172404604](https://www.pivotaltracker.com/n/projects/2192232/stories/172404604)
I think we should not put entanglement logic inside QuarksJob since it is not the feature of QuarksJob
Part of https://github.com/cloudfoundry-incubator/cf-operator/pull/909
=> Remove Entanglement code from Quarks Job

.travis.yml
[#172644852](https://www.pivotaltracker.com/story/show/172644852)
=> Preserve timestamps when publishing helm charts

.travis.yml, bin/include/docker, bin/include/versioning, bin/publish-helm-repo
Using `rev-list --count` gave us version 77 instead of 1176, or 92 instead of 1190.
We also had duplicate version numbers in separate PRs.
Travis creates a shallow git clone, so we unshallow it before counting
commits. We also add '--first-parent' for robustness.
[#172599056](https://www.pivotaltracker.com/story/show/172599056)
=> Fix development version by unshallowing git repo

.travis.yml, bin/build-helm, bin/deploy, bin/include/versioning
[#172599056](https://www.pivotaltracker.com/story/show/172599056)
=> Dev builds create pre-release helm charts/images

Makefile, bin/gen-kube, go.mod, go.sum, pkg/kubecodegen/pin.go
[172599016](https://www.pivotaltracker.com/story/show/172599016)
Depends on: https://github.com/cloudfoundry-incubator/quarks-utils/pull/45
Consume `gen-kube` from quarks-utils.
Caveat: it needs a checkout of quarks-utils. 
I couldn't still manage to make `go mod vendor` to download scripts in quarks-utils, but could be fixed by https://www.pivotaltracker.com/story/show/172645579 .
=> Consume gen-kube from quarks-utils

.github/workflows/publish.yml
Ignore only `creation of tags` event in publish job.
=> Fix publish workflow github action

README.md, docs/quarksjob.md, pkg/kube/controllers/quarksjob/output_persistor.go, pkg/kube/controllers/quarksjob/output_persistor_test.go
[#172993878](https://www.pivotaltracker.com/story/show/172993878)
=> Clean up persist output

deploy/helm/quarks-job/Chart.yaml
As described here helm/helm#9298 the invalid
string no longer works.
=> Fix build-helm.sh issue with Helm 3.5

deploy/helm/quarks-job/templates/_helpers.tpl, deploy/helm/quarks-job/templates/operator.yaml, go.mod, go.sum
Also reduce the other names, only prefix cluster-wide resources with
fullname.
[#175984792](https://www.pivotaltracker.com/story/show/175984792)
=> Use namespace to generate Release.fullname
